import './globals.css';
import Header from "./container/header"
import Footer from "./container/footer"
// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

// export default function RootLayout({
//   children,
// }: {
//   children: React.ReactNode
// }) {
//   return (
//     <html lang="en" dir='rtl'>
//       <body className="bg-blue-300">
//       <div className="bg-gray-300 h-full">
//             <Header />
//            <div className="bg-red-200 h-full container mx-auto lg:max-w-screen-xl">
//              {children}
//             </div>
//             <Footer />
//         </div>

//         </body>
//     </html>
//   )
// }
function Layout({ children }) {
  return (
    <html lang="en" dir="rtl" >
      <head>
        <meta />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>Document</title>
      </head>
      <body >
       <Header/>      
         <div className="bg-gray-50 min-h-screen rounded-3xl container mx-auto lg:max-w-screen-xl">
          {children}
        </div>
        {/* <Footer/> */}
      </body>
    </html>
  )

}
export default Layout